export const accountActionTypes = {
    SET_ACCOUNT: 'ACCOUNT.SET_ACCOUNT',
    SET_BAN_OBJECT: 'ACCOUNT.SET_BAN_OBJECT',
    SET_OTHER_PROFILE: 'ACCOUNT.SET_OTHER_PROFILE',
    SET_SCHEME: 'ACCOUNT.SET_SCHEME',
    SET_RECOMENDATIONS: 'ACCOUNT.SET_RECOMENDATIONS',
    SET_MYQUESTIONS: 'ACCOUNT.SET_MYQUESTIONS',
    SET_PUBLIC_STATUS: 'ACCOUNT.SET_PUBLIC_STATUS',

}
export const viewsActionTypes = {
    SET_ACTIVE_STORY: 'VIEWS.SET_ACTIVE_STORY',
    SET_ACTIVE_PANEL: 'VIEWS.SET_ACTIVE_PANEL',
    SET_ACTIVE_SCENE: 'VIEWS.SET_ACTIVE_SCENE',
    SET_HISTORY: 'VIEWS.SET_HISTORY',
    SET_NEED_EPIC: 'VIEWS.SET_NEED_EPIC',
    SET_SNACKBAR: 'VIEWS.SET_SNACKBAR',
}
export const tiketsActionTypes = {
    SET_TICKETS: 'TICKETS.SET_TICKETS',
    SET_TICKET: 'TICKETS.SET_TICKET',
    SET_COMMENT: 'TICKETS.SET_COMMENT',
    SET_OFFSET: 'TICKETS.SET_OFFSET',
    SET_TICKET_ID: 'TICKETS.SET_TICKET_ID'
}
export const moderationActionTypes = {
    SET_DATA: 'MODERATION.SET_DATA',
}
export const topUserActionTypes = { 
    SET_TOP: 'TOP_USERS.SET_TOP',
    SET_MODE: 'TOP_USERS.SET_MODE',
}
export const faqActionTypes = {
    SET_CATEGORIES: 'FAQ.SET_CATEGORIES',
    SET_QUESTIONS: 'FAQ.SET_QUESTIONS',
    SET_ACTIVE_CATEGORY: 'FAQ.SET_ACTIVE_CATEGORY',
    SET_ACTIVE_QUESTION: 'FAQ.SET_ACTIVE_QUESTION',
    SET_SEARCH_RESULT_QUESTION: 'FAQ.SET_SEARCH_RESULT_QUESTION',

}
export const reportsActionTypes = {
    SET_TYPE_REPORT: 'REP.SET_TYPE_REPORT',
    SET_RESOURCE_REPORT: 'REP.SET_RESOURCE_REPORT',
}