export const accountActionTypes = {
    SET_ACCOUNT: 'ACCOUNT.SET_ACCOUNT',
    SET_BAN_OBJECT: 'ACCOUNT.SET_BAN_OBJECT',
    SET_OTHER_PROFILE: 'ACCOUNT.SET_OTHER_PROFILE',
    SET_SCHEME: 'ACCOUNT.SET_SCHEME',
    SET_RECOMENDATIONS: 'ACCOUNT.SET_RECOMENDATIONS',
    SET_MYQUESTIONS: 'ACCOUNT.SET_MYQUESTIONS',
}
export const viewsActionTypes = {
    SET_ACTIVE_STORY: 'VIEWS.SET_ACTIVE_STORY',
    SET_NEED_EPIC: 'VIEWS.SET_NEED_EPIC',
}
export const tiketsActionTypes = {
    SET_TICKETS: 'TICKETS.SET_TICKETS',
    SET_TICKET: 'TICKETS.SET_TICKET',
    SET_COMMENT: 'TICKETS.SET_COMMENT',
}
export const moderationActionTypes = {
    SET_DATA: 'MODERATION.SET_DATA',
}